# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/uwo/Projects/PISR-NSGA-II

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/uwo/Projects/PISR-NSGA-II

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/uwo/Projects/PISR-NSGA-II/CMakeFiles /home/uwo/Projects/PISR-NSGA-II//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/uwo/Projects/PISR-NSGA-II/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pi_nsga2

# Build rule for target.
pi_nsga2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pi_nsga2
.PHONY : pi_nsga2

# fast build rule for target.
pi_nsga2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi_nsga2.dir/build.make CMakeFiles/pi_nsga2.dir/build
.PHONY : pi_nsga2/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi_nsga2.dir/build.make CMakeFiles/pi_nsga2.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi_nsga2.dir/build.make CMakeFiles/pi_nsga2.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi_nsga2.dir/build.make CMakeFiles/pi_nsga2.dir/main.cpp.s
.PHONY : main.cpp.s

src/numerical_solver.o: src/numerical_solver.cpp.o
.PHONY : src/numerical_solver.o

# target to build an object file
src/numerical_solver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi_nsga2.dir/build.make CMakeFiles/pi_nsga2.dir/src/numerical_solver.cpp.o
.PHONY : src/numerical_solver.cpp.o

src/numerical_solver.i: src/numerical_solver.cpp.i
.PHONY : src/numerical_solver.i

# target to preprocess a source file
src/numerical_solver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi_nsga2.dir/build.make CMakeFiles/pi_nsga2.dir/src/numerical_solver.cpp.i
.PHONY : src/numerical_solver.cpp.i

src/numerical_solver.s: src/numerical_solver.cpp.s
.PHONY : src/numerical_solver.s

# target to generate assembly for a file
src/numerical_solver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi_nsga2.dir/build.make CMakeFiles/pi_nsga2.dir/src/numerical_solver.cpp.s
.PHONY : src/numerical_solver.cpp.s

src/pde_problems.o: src/pde_problems.cpp.o
.PHONY : src/pde_problems.o

# target to build an object file
src/pde_problems.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi_nsga2.dir/build.make CMakeFiles/pi_nsga2.dir/src/pde_problems.cpp.o
.PHONY : src/pde_problems.cpp.o

src/pde_problems.i: src/pde_problems.cpp.i
.PHONY : src/pde_problems.i

# target to preprocess a source file
src/pde_problems.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi_nsga2.dir/build.make CMakeFiles/pi_nsga2.dir/src/pde_problems.cpp.i
.PHONY : src/pde_problems.cpp.i

src/pde_problems.s: src/pde_problems.cpp.s
.PHONY : src/pde_problems.s

# target to generate assembly for a file
src/pde_problems.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi_nsga2.dir/build.make CMakeFiles/pi_nsga2.dir/src/pde_problems.cpp.s
.PHONY : src/pde_problems.cpp.s

src/pi_solver.o: src/pi_solver.cpp.o
.PHONY : src/pi_solver.o

# target to build an object file
src/pi_solver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi_nsga2.dir/build.make CMakeFiles/pi_nsga2.dir/src/pi_solver.cpp.o
.PHONY : src/pi_solver.cpp.o

src/pi_solver.i: src/pi_solver.cpp.i
.PHONY : src/pi_solver.i

# target to preprocess a source file
src/pi_solver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi_nsga2.dir/build.make CMakeFiles/pi_nsga2.dir/src/pi_solver.cpp.i
.PHONY : src/pi_solver.cpp.i

src/pi_solver.s: src/pi_solver.cpp.s
.PHONY : src/pi_solver.s

# target to generate assembly for a file
src/pi_solver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi_nsga2.dir/build.make CMakeFiles/pi_nsga2.dir/src/pi_solver.cpp.s
.PHONY : src/pi_solver.cpp.s

src/tree_node.o: src/tree_node.cpp.o
.PHONY : src/tree_node.o

# target to build an object file
src/tree_node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi_nsga2.dir/build.make CMakeFiles/pi_nsga2.dir/src/tree_node.cpp.o
.PHONY : src/tree_node.cpp.o

src/tree_node.i: src/tree_node.cpp.i
.PHONY : src/tree_node.i

# target to preprocess a source file
src/tree_node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi_nsga2.dir/build.make CMakeFiles/pi_nsga2.dir/src/tree_node.cpp.i
.PHONY : src/tree_node.cpp.i

src/tree_node.s: src/tree_node.cpp.s
.PHONY : src/tree_node.s

# target to generate assembly for a file
src/tree_node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pi_nsga2.dir/build.make CMakeFiles/pi_nsga2.dir/src/tree_node.cpp.s
.PHONY : src/tree_node.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... pi_nsga2"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/numerical_solver.o"
	@echo "... src/numerical_solver.i"
	@echo "... src/numerical_solver.s"
	@echo "... src/pde_problems.o"
	@echo "... src/pde_problems.i"
	@echo "... src/pde_problems.s"
	@echo "... src/pi_solver.o"
	@echo "... src/pi_solver.i"
	@echo "... src/pi_solver.s"
	@echo "... src/tree_node.o"
	@echo "... src/tree_node.i"
	@echo "... src/tree_node.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

